### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by aliciabingham**

### CODE REVIEW

**Comment by zoeames** [comment]
@aliciamiceli is this ready for me to look at?

**Comment by aliciabingham** [comment]
@zoeames not even a little bit

**Comment by aliciabingham** [comment]
@zoeames ready now --- actually, no i'm not. one more commit. sorry

**Comment by aliciabingham** [comment]
@zoeames ok now for real

**Comment by zoeames** [comment]
looks like there are a couple of minor bugs with selecting robots BUT nothing major 👍

**Pull request merged**
